require "active_support/core_ext/integer/time"

LEVEL_COLORS = {
  "DEBUG" => "\e[90m",
  "INFO"  => "\e[0m",
  "WARN"  => "\e[33m",
  "ERROR" => "\e[31m",
  "FATAL" => "\e[31m\e[1m"
}.freeze

dev_formatter = proc do |severity, time, _progname, msg|
  color = LEVEL_COLORS.fetch(severity, "\e[0m")
  badge = severity[0]
  ts    = time.strftime("%H:%M:%S")
  "#{color}[#{badge}] #{ts}  #{msg}\e[0m\n"
end

Rails.application.configure do
  stdout_logger = ActiveSupport::Logger.new($stdout).tap { |l| l.formatter = dev_formatter }
  file_logger   = ActiveSupport::Logger.new(Rails.root.join("log/development.log"), 5, 50.megabytes)

  config.logger = ActiveSupport::TaggedLogging.new(
    ActiveSupport::BroadcastLogger.new(stdout_logger, file_logger)
  )

  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV["SMTP_ADRESS"],
    port: 587,
    user_name: ENV["SMTP_MAIL"],
    password: ENV["SMTP_PASSWORD"],
    authentication: "plain",
    enable_starttls_auto: true
  }
  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  config.active_record.verbose_query_logs = false
  config.active_record.query_log_tags_enabled = true
  config.active_job.verbose_enqueue_logs = false
  config.action_dispatch.verbose_redirect_logs = false

  # Lograge handles request logs at :info — suppress :debug SQL noise.
  config.log_level = :info

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
