name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: docker compose -f ./ci-cd/test/docker-compose.yml build

      - name: Run RSpec
        env:
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: docker compose -f ./ci-cd/test/docker-compose.yml up --exit-code-from test-runner --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker compose -f ./ci-cd/test/docker-compose.yml down -v
