name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose -f ./ci-cd/dev/docker-compose.yml build

      - name: Deploy
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          docker compose -f ./ci-cd/dev/docker-compose.yml down
          docker compose -f ./ci-cd/dev/docker-compose.yml up -d

      - name: Cleanup images
        run: docker image prune -f

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose -f ./ci-cd/prod/docker-compose.yml build

      - name: Deploy
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          docker compose -f ./ci-cd/prod/docker-compose.yml down
          docker compose -f ./ci-cd/prod/docker-compose.yml up -d

      - name: Cleanup images
        run: docker image prune -f
